# Generated by Django 6.0.5 on 2026-05-29 10:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productcode', models.TextField(db_column='productCode', unique=True)),
                ('name', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('outputquantity', models.FloatField(blank=True, db_column='outputQuantity', default=1.0, null=True)),
            ],
            options={
                'db_table': 'BOM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bomitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('materialname', models.TextField(db_column='materialName')),
                ('qty', models.FloatField()),
                ('unit', models.TextField()),
            ],
            options={
                'db_table': 'BOMItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'Brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('skuprefix', models.TextField(blank=True, db_column='skuPrefix', null=True)),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('stockmethod', models.TextField(db_column='stockMethod')),
            ],
            options={
                'db_table': 'Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dealercode', models.TextField(db_column='dealerCode', unique=True)),
                ('dealername', models.TextField(db_column='dealerName')),
                ('city', models.TextField()),
                ('assignedsoemail', models.TextField(db_column='assignedSoEmail')),
                ('distributorname', models.TextField(db_column='distributorName')),
                ('creditlimit', models.FloatField(db_column='creditLimit')),
                ('outstanding', models.FloatField()),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Dealer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('distributorname', models.TextField(db_column='distributorName', unique=True)),
                ('area', models.TextField()),
                ('assignedsoemail', models.TextField(db_column='assignedSoEmail')),
                ('creditlimit', models.FloatField(db_column='creditLimit')),
                ('outstanding', models.FloatField()),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Distributor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('category', models.TextField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('status', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('rejectreason', models.TextField(blank=True, db_column='rejectReason', null=True)),
                ('declaration', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Expense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('avgcost', models.FloatField(db_column='avgCost')),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('dailywage', models.FloatField(db_column='dailyWage', default=0.0)),
                ('contactinfo', models.TextField(blank=True, db_column='contactInfo', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Labour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'Market',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('orderid', models.TextField(db_column='orderId', unique=True)),
                ('date', models.DateTimeField()),
                ('partytype', models.TextField(db_column='partyType')),
                ('partyname', models.TextField(db_column='partyName')),
                ('distributor', models.TextField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('grandtotal', models.FloatField(db_column='grandTotal')),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('itemremark', models.TextField(blank=True, db_column='itemRemark', null=True)),
            ],
            options={
                'db_table': 'OrderItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productcode', models.TextField(db_column='productCode', unique=True)),
                ('name', models.TextField()),
                ('bagsize', models.TextField(db_column='bagSize')),
                ('rate', models.FloatField()),
                ('gst', models.FloatField()),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('openingstock', models.IntegerField(db_column='openingStock')),
                ('minimumstock', models.IntegerField(db_column='minimumStock')),
                ('defaultwarehouseid', models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('purchaseid', models.TextField(db_column='purchaseId', unique=True)),
                ('date', models.DateTimeField()),
                ('vendorname', models.TextField(db_column='vendorName')),
                ('grandtotal', models.FloatField(db_column='grandTotal')),
                ('status', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('challannumber', models.TextField(blank=True, db_column='challanNumber', null=True)),
                ('vehiclenumber', models.TextField(blank=True, db_column='vehicleNumber', null=True)),
                ('totaltax', models.FloatField(blank=True, db_column='totalTax', null=True)),
            ],
            options={
                'db_table': 'Purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productname', models.TextField(db_column='productName')),
                ('qty', models.IntegerField()),
                ('rate', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'PurchaseItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseorder',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ponumber', models.TextField(db_column='poNumber', unique=True)),
                ('date', models.DateTimeField()),
                ('expecteddate', models.DateTimeField(blank=True, db_column='expectedDate', null=True)),
                ('warehouseid', models.TextField(blank=True, db_column='warehouseId', null=True)),
                ('netamount', models.FloatField(db_column='netAmount')),
                ('totaltax', models.FloatField(db_column='totalTax')),
                ('status', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'PurchaseOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseorderitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productname', models.TextField(db_column='productName')),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('tax_percent', models.FloatField()),
                ('linetotal', models.FloatField(db_column='lineTotal')),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PurchaseOrderItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refreshtoken',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('userid', models.TextField(db_column='userId')),
                ('expiresat', models.DateTimeField(db_column='expiresAt')),
                ('revoked', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'RefreshToken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockbatch',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('cost', models.FloatField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'StockBatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('contactperson', models.TextField(blank=True, db_column='contactPerson', null=True)),
                ('contactinfo', models.TextField(blank=True, db_column='contactInfo', null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('gstnumber', models.TextField(blank=True, db_column='gstNumber', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'Unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('hashedpassword', models.TextField(db_column='hashedPassword')),
                ('role', models.TextField()),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userproductaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserProductAccess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userwarehouseaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserWarehouseAccess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('dealername', models.TextField(db_column='dealerName')),
                ('remarks', models.TextField()),
                ('nextfollowup', models.DateTimeField(blank=True, db_column='nextFollowup', null=True)),
                ('nextvisittime', models.DateTimeField(blank=True, db_column='nextVisitTime', null=True)),
                ('gpslocation', models.TextField(blank=True, db_column='gpsLocation', null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Visit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('gstnumber', models.TextField(blank=True, db_column='gstNumber', null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, db_column='companyName', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assignedTo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_leads', to='api.user')),
                ('companyid', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
                ('created_by', models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_leads', to='api.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_leads', to='api.user')),
            ],
            options={
                'db_table': 'Lead',
                'ordering': ['-updatedat'],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('VISIT', 'Visit'), ('MEETING', 'Meeting')], max_length=20)),
                ('notes', models.TextField()),
                ('next_followup_date', models.DateTimeField(blank=True, db_column='nextFollowupDate', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(db_column='leadId', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='api.lead')),
            ],
            options={
                'db_table': 'LeadFollowUp',
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_column='oldStatus', max_length=20)),
                ('new_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_column='newStatus', max_length=20)),
                ('changed_at', models.DateTimeField(db_column='changedAt', default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(db_column='changedBy', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
                ('lead', models.ForeignKey(db_column='leadId', on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='api.lead')),
            ],
            options={
                'db_table': 'LeadStageHistory',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='Lead_status_688a84_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'is_deleted'], name='Lead_assigne_bef42a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['createdat'], name='Lead_created_442693_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted'], name='Lead_isDelet_15ed0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='lead_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['lead', 'next_followup_date'], name='LeadFollowU_leadId_6eae35_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['createdat'], name='LeadFollowU_created_df43c1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstagehistory',
            index=models.Index(fields=['changed_at'], name='LeadStageHi_changed_8a25b1_idx'),
        ),
    ]
