# Generated by Django 6.0.5 on 2026-06-05 06:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productcode', models.TextField(db_column='productCode', unique=True)),
                ('name', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('outputquantity', models.FloatField(blank=True, db_column='outputQuantity', default=1.0, null=True)),
            ],
            options={
                'db_table': 'BOM',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('skuprefix', models.TextField(blank=True, db_column='skuPrefix', null=True)),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('stockmethod', models.TextField(db_column='stockMethod')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Refreshtoken',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('userid', models.TextField(db_column='userId')),
                ('expiresat', models.DateTimeField(db_column='expiresAt')),
                ('revoked', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'RefreshToken',
            },
        ),
        migrations.CreateModel(
            name='Bomitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('materialname', models.TextField(db_column='materialName')),
                ('qty', models.FloatField()),
                ('unit', models.TextField()),
                ('bomid', models.ForeignKey(db_column='bomId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bom')),
            ],
            options={
                'db_table': 'BOMItem',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('parentid', models.ForeignKey(blank=True, db_column='parentId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Category',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Brand',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='companyid',
            field=models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company'),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('distributorname', models.TextField(db_column='distributorName', unique=True)),
                ('area', models.TextField()),
                ('assignedsoemail', models.TextField(db_column='assignedSoEmail')),
                ('creditlimit', models.DecimalField(db_column='creditLimit', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('active', models.BooleanField()),
                ('territory', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Distributor',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, db_column='companyName', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(db_index=True, default=1)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Lead',
                'ordering': ['-updatedat'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dealercode', models.TextField(db_column='dealerCode', unique=True)),
                ('dealername', models.TextField(db_column='dealerName')),
                ('city', models.TextField()),
                ('assignedsoemail', models.TextField(db_column='assignedSoEmail')),
                ('distributorname', models.TextField(db_column='distributorName')),
                ('creditlimit', models.DecimalField(db_column='creditLimit', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('active', models.BooleanField()),
                ('territory', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
                ('converted_lead', models.OneToOneField(blank=True, db_column='convertedLeadId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_dealer', to='api.lead')),
            ],
            options={
                'db_table': 'Dealer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('orderid', models.TextField(db_column='orderId', unique=True)),
                ('date', models.DateTimeField()),
                ('partytype', models.TextField(db_column='partyType')),
                ('partyname', models.TextField(db_column='partyName')),
                ('distributor', models.TextField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('grandtotal', models.FloatField(db_column='grandTotal')),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productcode', models.TextField(db_column='productCode', unique=True)),
                ('name', models.TextField()),
                ('bagsize', models.TextField(db_column='bagSize')),
                ('rate', models.FloatField()),
                ('gst', models.FloatField()),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('openingstock', models.IntegerField(db_column='openingStock')),
                ('minimumstock', models.IntegerField(db_column='minimumStock')),
                ('defaultwarehouseid', models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True)),
                ('brandid', models.ForeignKey(blank=True, db_column='brandId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.brand')),
                ('categoryid', models.ForeignKey(db_column='categoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('itemremark', models.TextField(blank=True, db_column='itemRemark', null=True)),
                ('orderid', models.ForeignKey(db_column='orderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('purchaseid', models.TextField(db_column='purchaseId', unique=True)),
                ('date', models.DateTimeField()),
                ('vendorname', models.TextField(db_column='vendorName')),
                ('grandtotal', models.FloatField(db_column='grandTotal')),
                ('status', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('challannumber', models.TextField(blank=True, db_column='challanNumber', null=True)),
                ('vehiclenumber', models.TextField(blank=True, db_column='vehicleNumber', null=True)),
                ('totaltax', models.FloatField(blank=True, db_column='totalTax', null=True)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Purchase',
            },
        ),
        migrations.CreateModel(
            name='Purchaseitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productname', models.TextField(db_column='productName')),
                ('qty', models.IntegerField()),
                ('rate', models.FloatField()),
                ('total', models.FloatField()),
                ('purchaseid', models.ForeignKey(db_column='purchaseId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.purchase')),
            ],
            options={
                'db_table': 'PurchaseItem',
            },
        ),
        migrations.CreateModel(
            name='Purchaseorder',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ponumber', models.TextField(db_column='poNumber', unique=True)),
                ('date', models.DateTimeField()),
                ('expecteddate', models.DateTimeField(blank=True, db_column='expectedDate', null=True)),
                ('warehouseid', models.TextField(blank=True, db_column='warehouseId', null=True)),
                ('netamount', models.FloatField(db_column='netAmount')),
                ('totaltax', models.FloatField(db_column='totalTax')),
                ('status', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'PurchaseOrder',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaseorderid',
            field=models.ForeignKey(blank=True, db_column='purchaseOrderId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.purchaseorder'),
        ),
        migrations.CreateModel(
            name='Purchaseorderitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('productname', models.TextField(db_column='productName')),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('tax_percent', models.FloatField()),
                ('linetotal', models.FloatField(db_column='lineTotal')),
                ('remark', models.TextField(blank=True, null=True)),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('purchaseorderid', models.ForeignKey(db_column='purchaseOrderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.purchaseorder')),
            ],
            options={
                'db_table': 'PurchaseOrderItem',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Region',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('active', models.BooleanField()),
                ('regionid', models.ForeignKey(db_column='regionId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.region')),
            ],
            options={
                'db_table': 'Market',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('contactperson', models.TextField(blank=True, db_column='contactPerson', null=True)),
                ('contactinfo', models.TextField(blank=True, db_column='contactInfo', null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('gstnumber', models.TextField(blank=True, db_column='gstNumber', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplierid',
            field=models.ForeignKey(db_column='supplierId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplierid',
            field=models.ForeignKey(blank=True, db_column='supplierId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.supplier'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Unit',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unitid',
            field=models.ForeignKey(blank=True, db_column='unitId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.unit'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('hashedpassword', models.TextField(db_column='hashedPassword')),
                ('role', models.TextField()),
                ('active', models.BooleanField()),
                ('territory', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='soemail',
            field=models.ForeignKey(db_column='soEmail', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', to_field='email'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assignedTo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_leads', to='api.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(db_column='createdBy', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_leads', to='api.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedBy', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_leads', to='api.user'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('category', models.TextField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('status', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('rejectreason', models.TextField(blank=True, db_column='rejectReason', null=True)),
                ('declaration', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
                ('soemail', models.ForeignKey(db_column='soEmail', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', to_field='email')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
        migrations.CreateModel(
            name='Userproductaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandid', models.ForeignKey(blank=True, db_column='brandId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.brand')),
                ('categoryid', models.ForeignKey(blank=True, db_column='categoryId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('productid', models.ForeignKey(blank=True, db_column='productId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('userid', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'UserProductAccess',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('dealername', models.TextField(db_column='dealerName')),
                ('remarks', models.TextField()),
                ('nextfollowup', models.DateTimeField(blank=True, db_column='nextFollowup', null=True)),
                ('nextvisittime', models.DateTimeField(blank=True, db_column='nextVisitTime', null=True)),
                ('gpslocation', models.TextField(blank=True, db_column='gpsLocation', null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
                ('soemail', models.ForeignKey(db_column='soEmail', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', to_field='email')),
            ],
            options={
                'db_table': 'Visit',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('gstnumber', models.TextField(blank=True, db_column='gstNumber', null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('db_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_host', models.CharField(blank=True, max_length=200, null=True)),
                ('db_port', models.IntegerField(blank=True, null=True)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Warehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userwarehouseaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
                ('warehouseid', models.ForeignKey(db_column='warehouseId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse')),
            ],
            options={
                'db_table': 'UserWarehouseAccess',
            },
        ),
        migrations.CreateModel(
            name='Stockbatch',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('cost', models.FloatField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('warehouseid', models.ForeignKey(db_column='warehouseId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse')),
            ],
            options={
                'db_table': 'StockBatch',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouseid',
            field=models.ForeignKey(blank=True, db_column='warehouseId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('avgcost', models.FloatField(db_column='avgCost')),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('warehouseid', models.ForeignKey(db_column='warehouseId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('dailywage', models.FloatField(db_column='dailyWage', default=0.0)),
                ('contactinfo', models.TextField(blank=True, db_column='contactInfo', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company')),
            ],
            options={
                'db_table': 'Labour',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_column='oldStatus', max_length=20)),
                ('new_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_column='newStatus', max_length=20)),
                ('changed_at', models.DateTimeField(db_column='changedAt', default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(db_column='leadId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='api.lead')),
                ('changed_by', models.ForeignKey(db_column='changedBy', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'LeadStageHistory',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['changed_at'], name='LeadStageHi_changed_8a25b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('VISIT', 'Visit'), ('MEETING', 'Meeting')], max_length=20)),
                ('notes', models.TextField()),
                ('next_followup_date', models.DateTimeField(blank=True, db_column='nextFollowupDate', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(db_column='leadId', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='api.lead')),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followup_logs', to='api.user')),
            ],
            options={
                'db_table': 'LeadFollowUp',
                'ordering': ['-createdat'],
                'indexes': [models.Index(fields=['lead', 'next_followup_date'], name='LeadFollowU_leadId_6eae35_idx'), models.Index(fields=['createdat'], name='LeadFollowU_created_df43c1_idx'), models.Index(fields=['next_followup_date'], name='lead_followup_due_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='Lead_status_688a84_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'is_deleted'], name='Lead_assigne_bef42a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['createdat'], name='Lead_created_442693_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted'], name='Lead_isDelet_15ed0d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['companyid', 'status', 'priority'], name='Lead_company_7a0d50_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['companyid', 'assigned_to'], name='Lead_company_afa164_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['companyid', 'updatedat'], name='Lead_company_e388dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='lead_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='lead_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='lead_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('email', None), _negated=True), models.Q(('email', ''), _negated=True)), fields=('companyid', 'email'), name='unique_active_lead_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('phone', None), _negated=True), models.Q(('phone', ''), _negated=True)), fields=('companyid', 'phone'), name='unique_active_lead_phone_per_company'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'companyid')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('productid', 'warehouseid')},
        ),
    ]
