# Generated by Django 6.0.5 on 2026-05-29 10:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='version',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followup_logs', to='api.user'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['companyid', 'status', 'priority'], name='Lead_company_7a0d50_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['companyid', 'assigned_to'], name='Lead_company_afa164_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['companyid', 'updatedat'], name='Lead_company_e388dc_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['next_followup_date'], name='lead_followup_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='lead_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='lead_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('email', None), _negated=True), models.Q(('email', ''), _negated=True)), fields=('companyid', 'email'), name='unique_active_lead_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('phone', None), _negated=True), models.Q(('phone', ''), _negated=True)), fields=('companyid', 'phone'), name='unique_active_lead_phone_per_company'),
        ),
    ]
