# Generated by Django 6.0.5 on 2026-06-05 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktransaction',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('transactiontype', models.TextField(db_column='transactionType')),
                ('quantity', models.FloatField()),
                ('referenceid', models.TextField(blank=True, db_column='referenceId', null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('warehouseid', models.ForeignKey(blank=True, db_column='warehouseId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse')),
            ],
            options={
                'db_table': 'StockTransaction',
            },
        ),
    ]
