# Generated by Django 6.0.5 on 2026-06-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userwarehouseaccess',
        ),
    ]
