# Generated by Django 6.0.5 on 2026-08-02 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_remove_tenants_add_warehouse_fk'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitylog',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('user_email', models.TextField(blank=True, db_column='userEmail', null=True)),
                ('user_name', models.TextField(blank=True, db_column='userName', null=True)),
                ('user_role', models.TextField(blank=True, db_column='userRole', null=True)),
                ('log_type', models.TextField(db_column='logType', default='ACTION')),
                ('feature', models.TextField(default='General')),
                ('action', models.TextField()),
                ('details_json', models.TextField(blank=True, db_column='detailsJson', null=True)),
                ('ip_address', models.TextField(blank=True, db_column='ipAddress', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ActivityLog',
            },
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transactiontype', 'createdat'], name='idx_st_type_date'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='companyid',
            field=models.ForeignKey(blank=True, db_column='companyId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['log_type', 'createdat'], name='idx_actlog_type_date'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user_email', 'createdat'], name='idx_actlog_user_date'),
        ),
    ]
