# Generated by Django 6.0.5 on 2026-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_userwarehouseaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='distributorname',
            field=models.TextField(blank=True, db_column='distributorName', null=True),
        ),
    ]
