# Generated by Django 6.0.5 on 2026-08-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activitylog_stocktransaction_idx_st_type_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='status',
            field=models.TextField(default='PENDING_APPROVAL'),
        ),
    ]
