# Generated by Django 6.0.5 on 2026-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealercode',
            field=models.TextField(db_column='dealerCode'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='distributorname',
            field=models.TextField(db_column='distributorName'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productcode',
            field=models.TextField(db_column='productCode'),
        ),
        migrations.AddConstraint(
            model_name='dealer',
            constraint=models.UniqueConstraint(fields=('dealercode', 'companyid'), name='unique_dealer_per_company'),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(fields=('distributorname', 'companyid'), name='unique_distributor_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('productcode', 'companyid'), name='unique_product_per_company'),
        ),
    ]
