# Generated by Django 6.0.5 on 2026-08-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bom_status'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='warehouseid',
            field=models.ForeignKey(blank=True, db_column='warehouseId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouse'),
        ),
    ]
