# Generated by Django 6.0.5 on 2026-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dealer_distributorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatchdate',
            field=models.TextField(blank=True, db_column='dispatchDate', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatchwarehouse',
            field=models.TextField(blank=True, db_column='dispatchWarehouse', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='drivermobile',
            field=models.TextField(blank=True, db_column='driverMobile', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='drivername',
            field=models.TextField(blank=True, db_column='driverName', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoicenumber',
            field=models.TextField(blank=True, db_column='invoiceNumber', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vehiclenumber',
            field=models.TextField(blank=True, db_column='vehicleNumber', null=True),
        ),
    ]
