# Generated by Django 6.0.5 on 2026-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dealer_dealercode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='defaultwarehouseid',
            field=models.IntegerField(blank=True, db_column='defaultWarehouseId', null=True),
        ),
    ]
