# Generated by Django 6.0.5 on 2026-06-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brand_defaultwarehouseid_category_defaultwarehouseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='defaultwarehouseid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='defaultwarehouseid',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='defaultwarehouseid',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='defaultwarehouseid',
        ),
        migrations.RemoveField(
            model_name='labour',
            name='defaultwarehouseid',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='defaultwarehouseid',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='defaultwarehouseid',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='converted_lead',
            field=models.OneToOneField(blank=True, db_column='convertedLeadId', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_dealer', to='api.lead'),
        ),
    ]
