# Generated by Django 6.0.5 on 2026-06-26 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_dispatchdate_order_dispatchwarehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returnedqty',
            field=models.IntegerField(db_column='returnedQty', default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sentqty',
            field=models.IntegerField(db_column='sentQty', default=0),
        ),
        migrations.CreateModel(
            name='Dispatchlog',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dispatchdate', models.DateTimeField(db_column='dispatchDate', default=django.utils.timezone.now)),
                ('invoicenumber', models.TextField(blank=True, db_column='invoiceNumber', null=True)),
                ('vehiclenumber', models.TextField(blank=True, db_column='vehicleNumber', null=True)),
                ('drivername', models.TextField(blank=True, db_column='driverName', null=True)),
                ('drivermobile', models.TextField(blank=True, db_column='driverMobile', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('orderid', models.ForeignKey(db_column='orderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
            options={
                'db_table': 'DispatchLog',
            },
        ),
        migrations.CreateModel(
            name='Dispatchlogitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('dispatchlogid', models.ForeignKey(db_column='dispatchLogId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.dispatchlog')),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
            options={
                'db_table': 'DispatchLogItem',
            },
        ),
        migrations.CreateModel(
            name='Returnlog',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('returndate', models.DateTimeField(db_column='returnDate', default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('orderid', models.ForeignKey(db_column='orderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
            options={
                'db_table': 'ReturnLog',
            },
        ),
        migrations.CreateModel(
            name='Returnlogitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('returnlogid', models.ForeignKey(db_column='returnLogId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.returnlog')),
            ],
            options={
                'db_table': 'ReturnLogItem',
            },
        ),
    ]
