# Generated by Django 6.0.5 on 2026-06-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_brand_defaultwarehouseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='defaultwarehouseid',
        ),
    ]
