# Generated by Django 6.0.5 on 2026-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ledgerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerrequest',
            name='document_type',
            field=models.CharField(choices=[('LEDGER', 'Ledger'), ('BILL', 'Bill'), ('PRICELIST', 'Latest Price List'), ('OTHER', 'Other')], default='LEDGER', max_length=20),
        ),
        migrations.AddField(
            model_name='ledgerrequest',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerrequest',
            name='other_document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerrequest',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
