# Generated by Django 6.0.5 on 2026-06-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderitem_returnedqty_orderitem_sentqty_dispatchlog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warehouseid',
        ),
        migrations.DeleteModel(
            name='Refreshtoken',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='warehouseid',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Stockbatch',
        ),
    ]
