# Generated by Django 6.0.5 on 2026-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ledgerrequest_document_type_ledgerrequest_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerrequest',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerrequest',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
