# Generated by Django 6.0.5 on 2026-06-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_product_defaultwarehouseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthlytarget',
            field=models.FloatField(blank=True, db_column='monthlyTarget', null=True),
        ),
    ]
