# Generated by Django 6.0.5 on 2026-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_monthlytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
