# Generated by Django 6.0.5 on 2026-06-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchase_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lead',
            field=models.ForeignKey(blank=True, db_column='leadId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lead'),
        ),
    ]
