# Generated by Django 6.0.5 on 2026-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_busyparty_busyledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='distributorcode',
            field=models.TextField(blank=True, db_column='distributorCode', null=True, unique=True),
        ),
    ]
