# Generated by Django 6.0.5 on 2026-08-04 05:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dealer_address_dealer_contact_person_dealer_email_and_more'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('party_id', models.TextField(db_column='partyId')),
                ('party_name', models.TextField(db_column='partyName')),
                ('party_type', models.CharField(default='DEALER', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('submitted_by', models.ForeignKey(db_column='submittedById', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitted_payments', to='core.user')),
                ('verified_by', models.ForeignKey(blank=True, db_column='verifiedById', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_payments', to='core.user')),
            ],
            options={
                'db_table': 'PaymentReceipt',
            },
        ),
    ]
