# Generated by Django 6.0.5 on 2026-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_visit_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hr_remark',
            field=models.TextField(blank=True, db_column='hrRemark', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_column='verifiedAt', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='verified_by',
            field=models.CharField(blank=True, db_column='verifiedBy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_status',
            field=models.CharField(db_column='visitStatus', default='PENDING', max_length=20),
        ),
    ]
