# Generated by Django 6.0.5 on 2026-08-05 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paymentreceipt'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyOnboardingRequest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(default='DEALER', max_length=50)),
                ('party_name', models.CharField(max_length=255)),
                ('city_or_area', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('doc_aadhaar', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_pan', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_gst', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_address_proof', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_udhyam', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_security_cheque', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_person_photo', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_showroom_photo', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_party_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewedById', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_onboardings', to='core.user')),
                ('submitted_by', models.ForeignKey(db_column='submittedById', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitted_onboardings', to='core.user')),
            ],
            options={
                'db_table': 'PartyOnboardingRequest',
            },
        ),
    ]
