# Generated by Django 6.0.5 on 2026-07-03 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_distributor_distributorcode'),
        ('core', '0004_add_broadcast_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='warehouseid',
            field=models.ForeignKey(blank=True, db_column='warehouseId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='warehouseid',
            field=models.ForeignKey(blank=True, db_column='warehouseId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouse'),
        ),
    ]
