# Generated by Django 6.0.5 on 2026-08-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_partyonboardingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyonboardingrequest',
            name='doc_aadhaar',
        ),
        migrations.RemoveField(
            model_name='partyonboardingrequest',
            name='doc_security_cheque',
        ),
        migrations.RemoveField(
            model_name='partyonboardingrequest',
            name='doc_showroom_photo',
        ),
        migrations.AddField(
            model_name='partyonboardingrequest',
            name='doc_aadhaar_back',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partyonboardingrequest',
            name='doc_aadhaar_front',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partyonboardingrequest',
            name='doc_security_cheques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partyonboardingrequest',
            name='doc_showroom_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='partyonboardingrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_column='reviewedAt', null=True),
        ),
    ]
