# Generated by Django 6.0.5 on 2026-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_partyonboardingrequest_doc_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyonboardingrequest',
            name='doc_signed_form',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
