# Generated by Django 6.0.5 on 2026-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_partyonboardingrequest_doc_signed_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyonboardingrequest',
            name='extended_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
