# Generated by Django 6.0.5 on 2026-08-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_partyonboardingrequest_extended_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyonboardingrequest',
            name='doc_signed_form',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
