# Generated by Django 6.0.5 on 2026-08-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_partyonboardingrequest_doc_signed_form'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approvedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_transactions', to='core.user'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_transactions', to='core.user'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='delete_reason',
            field=models.TextField(blank=True, db_column='deleteReason', null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_stock_transactions', to='core.user'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='is_deleted',
            field=models.BooleanField(db_column='isDeleted', default=False),
        ),
    ]
