# Generated by Django 6.0.5 on 2026-08-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_stocktransaction_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='batches',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='expected_quantity',
            field=models.FloatField(blank=True, db_column='expectedQuantity', null=True),
        ),
    ]
