# Generated by Django 6.0.5 on 2026-08-16 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_stocktransaction_batches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='assignedsoemails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='assignedSoEmails', default=list, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='assignedsoemails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='assignedSoEmails', default=list, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='assignedsoemail',
            field=models.TextField(blank=True, db_column='assignedSoEmail', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='assignedsoemail',
            field=models.TextField(blank=True, db_column='assignedSoEmail', null=True),
        ),
    ]
