# Generated by Django 6.0.5 on 2026-08-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dealer_assignedsoemails_dealer_brand_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dealer',
            name='idx_dealer_so_active',
        ),
        migrations.RemoveIndex(
            model_name='distributor',
            name='idx_distributor_so_active',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='assignedsoemail',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='assignedsoemail',
        ),
    ]
