# Generated by Django 6.0.5 on 2026-08-18 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_dealer_idx_dealer_so_active_and_more'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('estimateid', models.TextField(db_column='estimateId', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('partyname', models.TextField(blank=True, db_column='partyName', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('grandtotal', models.FloatField(db_column='grandTotal', default=0.0)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'Estimate',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('itemremark', models.TextField(blank=True, db_column='itemRemark', null=True)),
                ('estimateid', models.ForeignKey(db_column='estimateId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.estimate')),
                ('productid', models.ForeignKey(db_column='productId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
            options={
                'db_table': 'EstimateItem',
                'indexes': [models.Index(fields=['estimateid', 'productid'], name='idx_estitem_est_prod')],
            },
        ),
    ]
