# Generated by Django 6.0.5 on 2026-08-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_estimate_estimateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
