# Generated by Django 6.0.5 on 2026-08-19 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_estimate_narration'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='bag_incentive_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='labour',
            name='base_salary_monthly',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='labour',
            name='employee_type',
            field=models.CharField(choices=[('FIXED', 'Fixed / Monthly'), ('VARIABLE', 'Variable / Daily')], default='VARIABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='labour',
            name='late_deduction_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='labour',
            name='overtime_hourly_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='labour',
            name='sales_incentive_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='labour',
            name='travel_allowance_per_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='labour',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'LeaveType',
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='LEAVE', max_length=20)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('labourid', models.ForeignKey(db_column='labourId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.labour')),
                ('leavetypeid', models.ForeignKey(blank=True, db_column='leaveTypeId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.leavetype')),
            ],
            options={
                'db_table': 'LeaveRecord',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_days', models.FloatField(default=0.0)),
                ('used_days', models.FloatField(default=0.0)),
                ('labourid', models.ForeignKey(db_column='labourId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.labour')),
                ('leavetypeid', models.ForeignKey(db_column='leaveTypeId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.leavetype')),
            ],
            options={
                'db_table': 'EmployeeLeaveBalance',
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('deduction_per_month', models.FloatField()),
                ('remaining_balance', models.FloatField()),
                ('date_issued', models.DateField()),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('labourid', models.ForeignKey(db_column='labourId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.labour')),
            ],
            options={
                'db_table': 'SalaryAdvance',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='PRESENT', max_length=20)),
                ('ot_hours', models.FloatField(default=0.0)),
                ('late_hours', models.FloatField(default=0.0)),
                ('km_travelled', models.FloatField(default=0.0)),
                ('bags_produced', models.FloatField(default=0.0)),
                ('sales_achieved', models.FloatField(default=0.0)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('labourid', models.ForeignKey(db_column='labourId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.labour')),
            ],
            options={
                'db_table': 'DailyAttendance',
                'unique_together': {('labourid', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('basic_pay', models.FloatField(default=0.0)),
                ('hra', models.FloatField(default=0.0)),
                ('allowances', models.FloatField(default=0.0)),
                ('ot_pay', models.FloatField(default=0.0)),
                ('incentives', models.FloatField(default=0.0)),
                ('gross_pay', models.FloatField(default=0.0)),
                ('advance_deduction', models.FloatField(default=0.0)),
                ('late_deduction', models.FloatField(default=0.0)),
                ('unpaid_leave_deduction', models.FloatField(default=0.0)),
                ('other_deductions', models.FloatField(default=0.0)),
                ('net_pay', models.FloatField(default=0.0)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('labourid', models.ForeignKey(db_column='labourId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.labour')),
            ],
            options={
                'db_table': 'SalarySlip',
                'unique_together': {('labourid', 'month')},
            },
        ),
    ]
