# Generated by Django 6.0.5 on 2026-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_labour_bag_incentive_rate_labour_base_salary_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='daily_advance',
            field=models.FloatField(default=0.0),
        ),
    ]
