# Generated by Django 6.0.5 on 2026-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_dailyattendance_daily_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='advance_medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='advance_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='advance_slip_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
