# Generated by Django 6.0.5 on 2026-08-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_dailyattendance_advance_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='is_bag_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labour',
            name='is_km_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labour',
            name='is_late_deduction_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labour',
            name='is_ot_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labour',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='api.labour'),
        ),
    ]
