# Generated by Django 6.0.5 on 2026-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_labour_department_labour_is_bag_eligible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour',
            old_name='travel_allowance_per_km',
            new_name='bike_allowance_per_km',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='actual_travel_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='travel_vehicle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='car_allowance_per_km',
            field=models.FloatField(default=0.0),
        ),
    ]
