# Generated by Django 6.0.5 on 2026-08-20 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_labour_designation_hrdepartment_hrdesignation'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='aadhar_photo',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='labour',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='bank_proof_photo',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='labour',
            name='doj',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='labour',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='employee_photo',
            field=models.FileField(blank=True, null=True, upload_to='hr/photos/'),
        ),
        migrations.AddField(
            model_name='labour',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labour',
            name='pan_photo',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/'),
        ),
        migrations.AddField(
            model_name='labour',
            name='user',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='core.user'),
        ),
    ]
