# Generated by Django 6.0.5 on 2026-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_labour_aadhar_number_labour_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='employee_type',
            field=models.CharField(choices=[('FIXED', 'Fixed / Monthly'), ('VARIABLE', 'Variable / Daily'), ('NONE', 'No Salary (Org Chart Only)')], default='VARIABLE', max_length=20),
        ),
    ]
