# Generated by Django 6.0.5 on 2026-08-20 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_labour_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='manual_advance_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('SALARY', 'Salary Payable'), ('ADVANCE', 'Salary Advance Given'), ('PAYMENT', 'Salary Payment Made'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labourid', models.ForeignKey(db_column='labourId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.labour')),
            ],
        ),
    ]
