# Generated by Django 6.0.5 on 2026-08-20 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_salaryslip_is_finalized_and_more'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('YEARLY', 'Yearly'), ('HALF_YEARLY', 'Half Yearly'), ('QUARTERLY', 'Quarterly'), ('BI_MONTHLY', 'Bi-Monthly'), ('MONTHLY', 'Monthly')], default='YEARLY', max_length=20)),
                ('days_to_allocate', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('department', models.ForeignKey(blank=True, db_column='departmentId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hrdepartment')),
                ('designation', models.ForeignKey(blank=True, db_column='designationId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hrdesignation')),
                ('leavetype', models.ForeignKey(db_column='leaveTypeId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.leavetype')),
            ],
            options={
                'db_table': 'LeavePolicy',
            },
        ),
        migrations.CreateModel(
            name='LeaveAllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('period_identifier', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('policy', models.ForeignKey(db_column='policyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.leavepolicy')),
            ],
            options={
                'db_table': 'LeaveAllocationLog',
                'unique_together': {('policy', 'period_identifier')},
            },
        ),
    ]
