# Generated by Django 6.0.5 on 2026-08-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_leavepolicy_leaveallocationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdesignation',
            name='department',
            field=models.ForeignKey(blank=True, db_column='departmentId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hrdepartment'),
        ),
    ]
