# Generated by Django 6.0.5 on 2026-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_hrdesignation_department'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hrdesignation',
            unique_together={('name', 'companyid', 'department')},
        ),
    ]
