# Generated by Django 6.0.5 on 2026-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_hrdesignation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
