# Generated by Django 6.0.5 on 2026-08-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_salaryslip_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeledger',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeledger',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
