# Generated by Django 6.0.5 on 2026-08-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_employeeledger_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='slip_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
