# Generated by Django 6.0.5 on 2026-09-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_salaryslip_slip_data'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='soemail',
            field=models.ForeignKey(blank=True, db_column='soEmail', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user', to_field='email'),
        ),
    ]
