# Generated by Django on 2026-09-18

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_estimate_soemail'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DailyTravelLog',
                    fields=[
                        ('id', models.TextField(primary_key=True, serialize=False)),
                        ('date', models.DateField()),
                        ('vehicle_type', models.CharField(default='BIKE', max_length=20)),
                        ('start_km', models.FloatField(default=0.0)),
                        ('end_km', models.FloatField(blank=True, null=True)),
                        ('total_km', models.FloatField(default=0.0)),
                        ('start_photo', models.TextField(blank=True, null=True)),
                        ('end_photo', models.TextField(blank=True, null=True)),
                        ('start_time', models.DateTimeField(blank=True, null=True)),
                        ('end_time', models.DateTimeField(blank=True, null=True)),
                        ('start_location', models.TextField(blank=True, null=True)),
                        ('end_location', models.TextField(blank=True, null=True)),
                        ('so_notes', models.TextField(blank=True, null=True)),
                        ('status', models.CharField(default='PENDING', max_length=20)),
                        ('approved_km', models.FloatField(blank=True, null=True)),
                        ('hr_notes', models.TextField(blank=True, null=True)),
                        ('verified_at', models.DateTimeField(blank=True, null=True)),
                        ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                        ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                        ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                        ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
                        ('verified_by', models.ForeignKey(blank=True, db_column='verifiedBy', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_travel_logs', to='core.user')),
                    ],
                    options={
                        'db_table': 'DailyTravelLog',
                        'unique_together': {('user', 'date')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS "DailyTravelLog" (
                        "id" text NOT NULL PRIMARY KEY,
                        "date" date NOT NULL,
                        "vehicle_type" varchar(20) NOT NULL DEFAULT 'BIKE',
                        "start_km" double precision NOT NULL DEFAULT 0.0,
                        "end_km" double precision NULL,
                        "total_km" double precision NOT NULL DEFAULT 0.0,
                        "start_photo" text NULL,
                        "end_photo" text NULL,
                        "start_time" timestamp with time zone NULL,
                        "end_time" timestamp with time zone NULL,
                        "start_location" text NULL,
                        "end_location" text NULL,
                        "so_notes" text NULL,
                        "status" varchar(20) NOT NULL DEFAULT 'PENDING',
                        "approved_km" double precision NULL,
                        "hr_notes" text NULL,
                        "verified_at" timestamp with time zone NULL,
                        "createdAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "updatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "companyId" text NOT NULL,
                        "userId" text NOT NULL,
                        "verifiedBy" text NULL
                    );
                    CREATE UNIQUE INDEX IF NOT EXISTS "DailyTravelLog_userId_date_uniq" ON "DailyTravelLog" ("userId", "date");
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "DailyTravelLog";',
                ),
            ],
        ),
    ]
