# Generated by Django 6.0.5 on 2026-09-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_dailytravellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytravellog',
            name='collection_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='order_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='visit_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
