# Generated by Django 6.0.5 on 2026-09-19 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_dailytravellog_collection_summary_and_more'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytravellog',
            name='performance_rating',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='target_achievement_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_actual_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_actual_bags',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_actual_collection',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_stops_planned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_stops_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_target_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_target_bags',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailytravellog',
            name='total_target_collection',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DailyTourPlanStop',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('stop_order', models.IntegerField(default=1)),
                ('is_unplanned', models.BooleanField(default=False)),
                ('dealer_id', models.TextField(blank=True, null=True)),
                ('dealer_name', models.CharField(max_length=255)),
                ('dealer_location', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_purpose', models.CharField(default='ORDER', max_length=50)),
                ('target_order_bags', models.FloatField(default=0.0)),
                ('target_order_value', models.FloatField(default=0.0)),
                ('target_collection_value', models.FloatField(default=0.0)),
                ('plan_notes', models.TextField(blank=True, null=True)),
                ('visited', models.BooleanField(default=False)),
                ('actual_order_bags', models.FloatField(default=0.0)),
                ('actual_order_value', models.FloatField(default=0.0)),
                ('actual_collection_value', models.FloatField(default=0.0)),
                ('actual_status', models.CharField(default='PENDING', max_length=40)),
                ('shortfall_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('actual_notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('travel_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.dailytravellog')),
                ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
            options={
                'db_table': 'DailyTourPlanStop',
                'indexes': [models.Index(fields=['user', 'date'], name='DailyTourPl_userId_97872e_idx'), models.Index(fields=['companyid', 'date'], name='DailyTourPl_company_1b84d0_idx')],
            },
        ),
    ]
