# Generated by Django 6.0.5 on 2026-09-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_dailytravellog_performance_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytourplanstop',
            name='visit_purpose',
            field=models.CharField(default='ORDER', max_length=255),
        ),
    ]
