# Generated by Django 6.0.5 on 2026-09-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_dailytourplanstop_visit_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytourplanstop',
            name='gps_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailytourplanstop',
            name='visit_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
