# Generated by Django 6.0.5 on 2026-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_dailytourplanstop_gps_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytourplanstop',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
