# Generated by Django 6.0.5 on 2026-09-20 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_dailytourplanstop_next_visit_date'),
        ('core', '0002_drop_obsolete_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('period_type', models.CharField(default='MONTHLY', max_length=20)),
                ('fiscal_year', models.CharField(default='2026-2027', max_length=20)),
                ('month', models.IntegerField(default=1)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('target_revenue', models.FloatField(default=0.0)),
                ('target_bags', models.FloatField(default=0.0)),
                ('target_collection', models.FloatField(default=0.0)),
                ('target_dealer_revenue', models.FloatField(default=0.0)),
                ('target_dealer_bags', models.FloatField(default=0.0)),
                ('target_non_dealer_revenue', models.FloatField(default=0.0)),
                ('target_non_dealer_bags', models.FloatField(default=0.0)),
                ('target_visits', models.IntegerField(default=0)),
                ('target_new_dealers', models.IntegerField(default=0)),
                ('target_travel_days', models.IntegerField(default=22)),
                ('category_targets', models.JSONField(blank=True, default=list)),
                ('product_targets', models.JSONField(blank=True, default=list)),
                ('min_achievement_pct_for_incentive', models.FloatField(default=80.0)),
                ('incentive_per_bag', models.FloatField(default=0.0)),
                ('incentive_pct_on_revenue', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to='core.user')),
                ('user', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_targets', to='core.user')),
            ],
            options={
                'db_table': 'SalesTarget',
                'indexes': [models.Index(fields=['companyid', 'fiscal_year', 'month'], name='SalesTarget_company_9e0f94_idx'), models.Index(fields=['user', 'fiscal_year', 'month'], name='SalesTarget_userId_8aa3ed_idx')],
                'unique_together': {('companyid', 'user', 'period_type', 'fiscal_year', 'month')},
            },
        ),
    ]
