# Generated by Django 6.0.5 on 2026-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_salestarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestarget',
            name='custom_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='incentive_slabs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='min_collection_pct_for_incentive',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='new_dealer_bounty',
            field=models.FloatField(default=500.0),
        ),
    ]
