# Generated by Django 6.0.5 on 2026-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_salestarget_custom_targets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='party_type',
            field=models.CharField(db_column='partyType', default='DEALER', max_length=50),
        ),
    ]
