@echo off
echo KILLING NODE PROCESSES...
taskkill /F /IM node.exe /T 2>NUL
echo STARTING BACKEND...
start "BACKEND" /B cmd /c "cd backend && npm run dev > ..\backend_log.txt 2>&1"
echo STARTING FRONTEND...
start "FRONTEND" /B cmd /c "cd frontend && npm run dev > ..\frontend_log.txt 2>&1"
echo SERVERS INITIATED. CHECK backend_log.txt and frontend_log.txt
