# Generated by Django 6.0.5 on 2026-07-27 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('core', '0001_initial'),
        ('core', '0002_userwarehouseaccess'),
        ('core', '0003_add_settings_json_to_company'),
        ('core', '0004_add_broadcast_model'),
    ]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('skuprefix', models.TextField(blank=True, db_column='skuPrefix', null=True)),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('stockmethod', models.TextField(db_column='stockMethod')),
                ('settings_json', models.TextField(blank=True, db_column='settingsJson', default='{}', null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('target_role', models.CharField(db_column='targetRole', default='ALL', max_length=30)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'Broadcast',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('hashedpassword', models.TextField(db_column='hashedPassword')),
                ('role', models.TextField()),
                ('active', models.BooleanField()),
                ('monthlytarget', models.FloatField(blank=True, db_column='monthlyTarget', null=True)),
                ('territory', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('gstnumber', models.TextField(blank=True, db_column='gstNumber', null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'Warehouse',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.CreateModel(
            name='Userwarehouseaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
                ('warehouseid', models.ForeignKey(db_column='warehouseId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouse')),
            ],
            options={
                'db_table': 'UserWarehouseAccess',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('is_primary', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.warehouse')),
            ],
            options={
                'db_table': 'Domain',
            },
        ),
    ]
