# Generated by Django 6.0.5 on 2026-06-14 16:54

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('skuprefix', models.TextField(blank=True, db_column='skuPrefix', null=True)),
                ('active', models.BooleanField()),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('stockmethod', models.TextField(db_column='stockMethod')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('hashedpassword', models.TextField(db_column='hashedPassword')),
                ('role', models.TextField()),
                ('active', models.BooleanField()),
                ('monthlytarget', models.FloatField(blank=True, db_column='monthlyTarget', null=True)),
                ('territory', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('gstnumber', models.TextField(blank=True, db_column='gstNumber', null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('db_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_host', models.CharField(blank=True, max_length=200, null=True)),
                ('db_port', models.IntegerField(blank=True, null=True)),
                ('companyid', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'Warehouse',
                'unique_together': {('name', 'companyid')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.warehouse')),
            ],
            options={
                'db_table': 'Domain',
            },
        ),
    ]
