# Generated by Django 6.0.5 on 2026-06-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userwarehouseaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(db_column='userId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
                ('warehouseid', models.ForeignKey(db_column='warehouseId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouse')),
            ],
            options={
                'db_table': 'UserWarehouseAccess',
            },
        ),
    ]
