# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_remove_tenants_add_warehouse_fk'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "Warehouse" DROP COLUMN IF EXISTS schema_name;',
                'ALTER TABLE "Warehouse" DROP COLUMN IF EXISTS db_name;',
                'ALTER TABLE "Warehouse" DROP COLUMN IF EXISTS db_host;',
                'ALTER TABLE "Warehouse" DROP COLUMN IF EXISTS db_port;',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
