# Generated by Django 6.0.5 on 2026-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userwarehouseaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='settings_json',
            field=models.TextField(blank=True, db_column='settingsJson', default='{}', null=True),
        ),
    ]
