# Generated by Django 6.0.5 on 2026-06-20 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_settings_json_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('target_role', models.CharField(db_column='targetRole', default='ALL', max_length=30)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(db_column='companyId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
            ],
            options={
                'db_table': 'Broadcast',
                'ordering': ['-created_at'],
            },
        ),
    ]
